-- Autogenerated from sql_create.template 
-- Time: 2021-03-04 18:38:53.825085
-- Database: mysql

CREATE TABLE Fakultet (
    naziv varchar 
            PRIMARY KEY
            ,
    godina_osnivanja number 
            UNIQUE
            NOT NULL
            ,
    grad varchar 
            NOT NULL
            ,
    hello varchar 
            UNIQUE
            ,
    naziv_copied varchar 
);

CREATE TABLE Student (
    id integer 
            PRIMARY KEY
            ,
    indeks integer 
);

