-- Autogenerated from sql_create.template 
-- Database: mysql


CREATE TABLE Fakultet (
    name varchar,
    city varchar,
    hello varchar,
    name_copied varchar,
);


CREATE TABLE Student (
    id integer,
    indeks integer,
);

