-- Autogenerated from sql_create.template 
-- Time: 2021-03-06 18:54:44.188053
-- Database: mysql

CREATE TABLE Fakultet (
    naziv varchar 
            PRIMARY KEY
            ,
    godina_osnivanja number 
            UNIQUE
            NOT NULL
            ,
    grad varchar 
            NOT NULL
            ,
    hello varchar 
            UNIQUE
            ,
    naziv_copied varchar 
);

CREATE TABLE Predmet (
    naziv varchar 
            PRIMARY KEY
            ,
    broj_bodova number 
            NOT NULL
);

CREATE TABLE Student_Fakultet (
    id number 
            PRIMARY KEY
            ,
    student_id integer 
            ,
    fakultet_naziv varchar 
);

CREATE TABLE Student_Predmet (
    id number 
            PRIMARY KEY
            ,
    student_id integer 
            ,
    predmet_naziv varchar 
);

CREATE TABLE Student (
    id integer 
            PRIMARY KEY
            ,
    indeks integer 
);

