-- Autogenerated from sql_create.template
-- Time: 20.04.2021. 13:51
-- Database: mysql

CREATE TABLE Owner (
    id INT UNSIGNED PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE PublishingHouse (
    id INT UNSIGNED PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE City (
    id INT UNSIGNED PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE Bookstore (
    id INT UNSIGNED PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255),
    zipcode INT UNSIGNED,
    city_id_bookstoresincity INT UNSIGNED,
    FOREIGN KEY (city_id_bookstoresincity) REFERENCES City(id)
);

CREATE TABLE Book (
    id INT UNSIGNED PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    author VARCHAR(255),
    isbn VARCHAR(255) UNIQUE NOT NULL,
    bookstore_id_publishedbooks INT UNSIGNED,
    FOREIGN KEY (bookstore_id_publishedbooks) REFERENCES Bookstore(id),
    publishinghouse_id_book INT UNSIGNED,
    FOREIGN KEY (publishinghouse_id_book) REFERENCES PublishingHouse(id)
);

CREATE TABLE Bookstore_Owner (
    bookstore_id INT UNSIGNED,
    FOREIGN KEY (bookstore_id) REFERENCES Bookstore(id),
    owner_id INT UNSIGNED,
    FOREIGN KEY (owner_id) REFERENCES Owner(id)
);

