-- Autogenerated from sql_create.template
-- Time: 20.04.2021. 15:03
-- Database: mysql

CREATE TABLE Fakultet (
    naziv VARCHAR(255) PRIMARY KEY,
    godina_osnivanja INT UNSIGNED UNIQUE NOT NULL,
    grad VARCHAR(255) NOT NULL,
    hello VARCHAR(255) UNIQUE,
    naziv_copied VARCHAR(255)
);

CREATE TABLE Student (
    id INT UNSIGNED PRIMARY KEY,
    indeks INT UNSIGNED
);

CREATE TABLE Predmet (
    naziv VARCHAR(255) PRIMARY KEY,
    broj_bodova INT UNSIGNED NOT NULL
);

CREATE TABLE Student_Fakultet (
    student_id INT UNSIGNED,
    FOREIGN KEY (student_id) REFERENCES Student(id),
    fakultet_naziv VARCHAR(255),
    FOREIGN KEY (fakultet_naziv) REFERENCES Fakultet(naziv)
);

CREATE TABLE Student_Predmet (
    student_id INT UNSIGNED,
    FOREIGN KEY (student_id) REFERENCES Student(id),
    predmet_naziv VARCHAR(255),
    FOREIGN KEY (predmet_naziv) REFERENCES Predmet(naziv)
);

