-- Autogenerated from sql_create.template
-- Time: 19.04.2021. 23:18
-- Database: mysql

CREATE TABLE Magacin (
    id INT UNSIGNED PRIMARY KEY,
    status BOOLEAN
);

CREATE TABLE Proizvod (
    naziv VARCHAR(255),
    barkod INT UNSIGNED UNIQUE,
    tip VARCHAR(255),
    brojnoStanje INT UNSIGNED,
    kapacitet INT UNSIGNED,
    id INT UNSIGNED PRIMARY KEY,
    status BOOLEAN
);

CREATE TABLE Korisnik (
    kontakt VARCHAR(255),
    ime VARCHAR(255) NOT NULL,
    prezime VARCHAR(255),
    adresa VARCHAR(255),
    id INT UNSIGNED PRIMARY KEY,
    status BOOLEAN,
    magacin_id_korisnik INT UNSIGNED,
    FOREIGN KEY (magacin_id_korisnik) REFERENCES Magacin(id)
);

CREATE TABLE Transakcija (
    vreme TIMESTAMP NOT NULL,
    barkod INT UNSIGNED UNIQUE,
    tipTransakcije INT UNSIGNED,
    kolicina INT UNSIGNED,
    id INT UNSIGNED PRIMARY KEY,
    status BOOLEAN,
    korisnik_id_transakcija INT UNSIGNED,
    FOREIGN KEY (korisnik_id_transakcija) REFERENCES Korisnik(id)
);

CREATE TABLE Istorija (
    id INT UNSIGNED PRIMARY KEY,
    status BOOLEAN,
    transakcija_id_transakcija INT UNSIGNED,
    FOREIGN KEY (transakcija_id_transakcija) REFERENCES Transakcija(id),
    magacin_id_istorija INT UNSIGNED,
    FOREIGN KEY (magacin_id_istorija) REFERENCES Magacin(id)
);

CREATE TABLE Sektor (
    lokacija VARCHAR(255),
    id INT UNSIGNED PRIMARY KEY,
    status BOOLEAN,
    magacin_id_sektor INT UNSIGNED,
    FOREIGN KEY (magacin_id_sektor) REFERENCES Magacin(id)
);

CREATE TABLE Slot (
    kapacitet INT UNSIGNED,
    lokacija VARCHAR(255),
    id INT UNSIGNED PRIMARY KEY,
    status BOOLEAN,
    sektor_id_slot INT UNSIGNED,
    FOREIGN KEY (sektor_id_slot) REFERENCES Sektor(id)
);

